#!/bin/bash
# post-export-graph.sh - Auto-generate Mermaid dependency graph after bd export
# Installed by: beads-init.sh (as a post-export hook in .beads/config.yaml)
# Gracefully skips if bv is not installed or no beads data exists.

set -euo pipefail

# Graceful degradation: skip if bv not available
if ! command -v bv &>/dev/null; then
    exit 0
fi

# Skip if no beads data
if [ ! -f .beads/beads.jsonl ] && [ ! -f .beads/issues.jsonl ]; then
    exit 0
fi

# Generate graph
GRAPH_OUTPUT="$(bv --robot-graph --fmt mermaid 2>/dev/null)" || exit 0

# Skip if empty output
if [ -z "$GRAPH_OUTPUT" ]; then
    exit 0
fi

HEADER="<!-- Auto-generated by bv. Do not edit manually. -->"
FULL_CONTENT="$HEADER
# Dependency Graph

\`\`\`mermaid
$GRAPH_OUTPUT
\`\`\`
"

# Only write if content has changed (avoids noisy git diffs)
TARGET="docs/dependency-graph.md"
if [ -f "$TARGET" ]; then
    EXISTING="$(cat "$TARGET")"
    if [ "$EXISTING" = "$FULL_CONTENT" ]; then
        exit 0
    fi
fi

# Create docs/ directory only when needed
mkdir -p docs
printf '%s' "$FULL_CONTENT" > "$TARGET"
